### ISSUE TITLE
Issue a new branch naming pattern

### ISSUE THREAD

**Issue by hamzaplojovic** [edinmavric/frontend#2]
We need to issue a new branch naming pattern, for easier code management, and version control. It should be like:

`initials\feature or issue` => `em\main-page`

or something similar, because it will enable us to have one purpose branches, that we can delete after merging to the main branch.

**Comment by edinmavric** [comment]
i created new branch earlier and i was working on it, no commits, named it "page-style". 

git checkout -b em/style-page?

Can i just create and switch on new branch or do i need to save something?

**Comment by hamzaplojovic** [comment]
You should first push the code with that branch with `git push`.

Then, you run git checkout -b "em/something" to create a branch with the newest code with our new branch pattern.

Then, you push that branch, and delete the other one, and you are left with the branch with the code you are working on, that follows the pattern.

**Comment by hamzaplojovic** [comment]
Also, I will write an issue regarding communication with discord or some other service that we can add channels for different parts of project, and we can even have daily meetups that are around 10 to 15 minutes to discuss work for that day. What do you thing?

**Comment by edinmavric** [comment]
Discord sounds good! Also i created new branch with the changes.

branch name: "em/style-page"

**Comment by hamzaplojovic** [comment]
Okay, be sure to push the branch and make a PR when you want to merge it on `main`. Also, here is the discord link. I will delete the invitation link, when you send me a message there that you got in the server.

https://discord.gg/CV3gxuFq
